apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  TZ: Europe/Berlin
  server.port: "${_Values_service_port}"

  #monitoring
  management.database.monitoring.enabled: "true"
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"
  management.endpoint.health.show-details: always

  server.tomcat.threads.max: "20"
  security.authentication.enabled: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
stringData:
  #datasource
  database.provisioning.goals: -migrate

  spring.datasource.url: "jdbc:postgresql://country-service-postgres:5432/country"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  #adapter
  adapter.calleeservice.url: "http://callee-service-application:8080"

  adapter.timeout: "10000"
  resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold: "10000"
  resilience4j.circuitbreaker.configs.default.failureRateThreshold: "30"
#  resilience4j.circuitbreaker.configs.default.ignoreExceptions: "java.lang.Exception"

data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: ZXhhbXBsZXVzZXI=
  adapter.calleeservice.password: RU5DKExnQ1Q0a3JXNU5EclFrZkdQUEVZdzdYT3Z6dWZ2SUFOV0ZxM3ZIb3crU3BoZDZBQ3RhdmFoVzhhTDI4TkRubVpleDUrUG56MTRORWVEdVIrWkk5MHNRPT0p