replicaCount: 1

tenantId: 0
namespace: example-tenant-0
ingress:
  paths: /callee/{{ .Values.tenantId }}
  enabled: true

image:
  repository: "goafabric/callee-service-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx16M"]

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080