apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiali-ingress
  namespace: istio-system
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer

    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    nginx.ingress.kubernetes.io/rewrite-target: /kiali/\$2

    # basic auth
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: authentication-secret


spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${_Values_host_name}
      secretName: root-certificate
  rules:
    - host: ${_Values_host_name}
      http:
        paths:
          - path: /kiali(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kiali
                port:
                  number: 20001
           

