apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${_Values_app_name}
  namespace: ${_Release_namespace}
  labels:
    app: ${_Values_app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${_Values_app_name}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        sidecar.istio.io/inject: "false"
      labels:
        app: ${_Values_app_name}
    spec:
      containers:
      - name: ${_Values_app_name}
        image: quay.io/keycloak/keycloak:22.0.0

        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443

        envFrom:
          - configMapRef:
              name: ${_Values_app_name}-config
          - secretRef:
              name: ${_Values_app_name}-config-external

        args: ["start"]

        readinessProbe:
          httpGet:
            path: /oidc/realms/master
            port: 8080
          initialDelaySeconds: 5
