replicaCount: 1

image:
  repository: "postgres"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "false"

resources:
  requests:
    memory: 64M
    cpu: 250m
  limits:
    cpu: 500m

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 5432

postgres:
  maxConnections: 30

persistence:
  storageClassName: