apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config-log
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #log levels
  quarkus.log.level: "INFO"
#  quarkus.log.category."org.goafabric".level: "INFO"
#  quarkus.log.category."org.flywaydb.core".level: "INFO"
#  quarkus.log.category."org.hibernate".level: "INFO"
