apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welcome-board-application-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # basic auth
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: authentication-secret

spec:
  tls:
    - hosts:
        - kubernetes
      secretName: server-certificate-secret
  rules:
    - host: kubernetes
      http:
        paths:
          - path: /welcome(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: welcome-board-application
                port:
                  number: 8080