apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}

data:
  spring.datasource.username: cGVyc29uLXNlcnZpY2U=
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  quarkus.datasource.username: cGVyc29uLXNlcnZpY2U=
  quarkus.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: WVdSdGFXND0=
  adapter.calleeservice.password: WVdSdGFXND0=

  security.encryption.key: "MjAzZmVmOTAtYWVhZC00NWNhLTgzMGUtY2E4NzhiYjRlOTg3" #this needs to be changed during first deployment to an unique value