apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "{{ .Values.service.port }}"
  quarkus.http.io-threads: "20"

  #security
  security.authentication.enabled: "false"

  #jaeger
  quarkus.jaeger.service-name: "{{ include "application.fullname" . }}"

  quarkus.jaeger.endpoint: "http://jaeger-collector.monitoring:14268/api/traces"
  quarkus.jaeger.sampler-type: "probabilistic"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.propagation: "b3"

  #tracing
  quarkus.otel.exporter.otlp.traces.endpoint: "http://jaeger-collector.monitoring:4317"
  quarkus.application.name: { { include "application.fullname" . } }

  #persistence
  quarkus.datasource.jdbc.url: "jdbc:postgresql://person-service-postgres:5432/person"
  quarkus.datasource.jdbc.max-size: "10"

  database.provisioning.goals: "-import-demo-data"

  #adapter
  adapter.calleeservice.url: "http://callee-service-application:8080"

  adapter.timeout: "10000"
  adapter.failureRate: "0.5"
  adapter.openDuration: "30000"
  adapter.circuitBreaker.enabled: "true"