replicaCount: 1

image:
  repository: "goafabric/person-service"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: disable
  sidecar.istio.io/inject: "false"

resourcesAnnotations:
  resources:
    requests:
      memory: 256M
      cpu: 250m

  command: ["java", "-Xms256M", "-Xmx256M", "-cp", "/app/resources:/app/classes:/app/libs/*", "org.goafabric.personservice.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]
  
initContainers:
  - name: wait-for-application
    image: curlimages/curl:7.75.0
    command: ["/bin/sh","-c"]
    args: ["while [ $(curl -sw '%{http_code}' --fail --connect-timeout 1 http://person-service-application:8080/actuator/health -o /dev/null) -ne 200 ]; do sleep 2; done"]

