replicaCount: 1

tenantId: 5a2f
ingress:
  paths: /person/{{ .Values.tenantId }}
  enabled: true

image:
  repository: "goafabric/person-service-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx16M"]

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:14.0
    command: ['sh', '-c','until pg_isready -h person-service-postgres -p 5432;do echo waiting for database; sleep 1; done;']