apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-secret
  labels:
    {{- include "application.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: person
data:
  POSTGRES_USER: cGVyc29uLXNlcnZpY2U=
  POSTGRES_PASSWORD: Y3JOYjJaNm12QnlTUkt3dQ==

  #echo -n person-service | base64
  #echo -n crNb2Z6mvBySRKwu | base64
  #echo -n Y3JOYjJaNm12QnlTUkt3dQ== | base64 -d